---
- name: Create a micro instance
  hosts: localhost
  gather_facts: false
  vars:
    keypair: clave-lucatic
    instance_type: t2.micro
    security_group: sg-013c0f1d5466fd440
    subnet_id: subnet-02d7d287d60aad6c3
    image: ami-0b752bf1df193a6c4
    region: eu-west-1
  tasks:
    - name: Launch instance
      amazon.aws.ec2_instance:
         key_name: "{{ keypair }}"
         security_group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image_id: "{{ image }}"
         state: running
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet_id }}"
         network:   
           assign_public_ip: yes
         tags:
           Name: ansibleInstance
           APP: vue2048
      register: ec2

    - name: Print ec2_instance return information
      ansible.builtin.debug:
        var: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: launched
      loop: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user
      loop: "{{ ec2.instances }}"

- name: Configure instance(s)
  hosts: launched
  become: true
  gather_facts: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: latest

    - name: Start Apache HTTP Server
      service:
        name: httpd
        state: started

