---
- name: Disable Docker and install Apache HTTP Server
  hosts: all
  become: true
  
  tasks:
    - name: Disable Docker service
      service:
        name: docker
        state: stopped
        enabled: false
    
    - name: Install Apache HTTP Server
      yum:
        name: httpd
        state: latest
          
    - name: Start Apache HTTP Server
      service:
        name: httpd
        state: started
      
    - name: Create directory /app
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Clone the repository ZIP to /app
      command: wget https://github.com/alvarodcr/hello-2048/archive/refs/heads/main.zip
      
    - name: Move main.zip yo /app
      command: mv main.zip /home/ec2-user/app/main.zip
        
    - name: Unzip main.zip
      command: unzip /home/ec2-user/main.zip

    - name: Move contents to remote directory
      copy:
        src: /home/app/hello-2048-main/public_html/
        dest: /var/www/html/
        mode: 0755
        directory_mode: 0755

    - name: Check Apache HTTP Server is running after reboot
      command: systemctl is-active apache2
      register: result
