---
- name: Install hello-2048
  hosts: all
  become: true
  vars:
    ansible_user: ec2-user

  tasks:

    - name: Create directory /app
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Clone the repository ZIP to /app
      command: wget https://github.com/alvarodcr/hello-2048/archive/refs/heads/main.zip

    - name: Move main.zip to /app
      command: mv /home/ec2-user/main.zip /home/ec2-user/app/

    - name: Unzip main.zip
      command: unzip /home/ec2-user/app/main.zip

    - name: Move contents to remote directory
      copy:
        src: /home/ec2-user/app/hello-2048-main/public_html/
        dest: /var/www/html/
        mode: 0755
        directory_mode: 0755



